export const products = [
    {
        id: 1,
        name: "Intel Core i7-13700K Desktop Processor 16 Cores (8 P-cores + 8 E-cores)",
        category: "CPU",
        price: 380,
        image: "/images/products/intelcpu.jpg",
        isCart: false,
        description: "16 cores (8 P-cores + 8 E-cores) and 24 threads, Up to 5.4 GHz unlocked. 30M Cache, Integrated Intel UHD Graphics 770 included, Compatible with Intel 600 series (might need BIOS update) and 700 series chipset-based motherboards",
    },
    {
        id: 2,
        name: "AMD Ryzen™ 7 5800X3D 8-core, 16-Thread Desktop Processor",
        category: "CPU",
        price: 320,
        image: "/images/products/amdcpu.jpg",
        isCart: false,
        description: "8 Cores and 16 processing threads with AMD 3D V-Cache technology, 4.5 GHz Max Boost, 100 MB cache, DDR4-3200 support, For the advanced Socket AM4 platform, can support PCIe 4.0 on X570 and B550 motherboards",
    },
    {
        id: 3,
        name: "ASUS Dual GeForce RTX™ 4060 OC Edition 8GB GDDR6 (PCIe 4.0, 8GB GDDR6, DLSS 3, HDMI 2.1a, DisplayPort 1.4a, 2.5-Slot Design",
        category: "GPU",
        price: 300,
        image: "/images/products/gpunvidia.jpg",
        isCart: false,
        description: "NVIDIA Ada Lovelace Streaming Multiprocessors: Up to 2X performance and power efficiency, 4th Generation Tensor Cores: Up to 4x performance with DLSS 3 vs. brute-force rendering, 3rd Generation RT Cores: Up to 2x ray tracing performance",
    },
    {
        id: 4,
        name: "GIGABYTE GV-R76GAMING OC-8GD Radeon RX 7600 Gaming OC 8G Graphics Card, 3X WINDFORCE Fans 8GB 128-bit GDDR6",
        category: "GPU",
        price: 260,
        image: "/images/products/gpuradeon.jpg",
        isCart: false,
        description: "Integrated with 8GB GDDR6 128-bit memory interface, PCI Express 4.0 Support, WINDFORCE cooling system, RGB Fusion, Protection metal backplate, HDMI 2.1 x1, DisplayPort 2.1 x2",
    },
    {
        id: 5,
        name: "Corsair Vengeance LPX 16GB (2x8GB) DDR4 DRAM 3200MHz C16 Desktop Memory Kit - Black (CMK16GX4M2B3200C16)",
        category: "RAM",
        price: 40,
        image: "/images/products/ramddr4.jpg",
        isCart: false,
        description: "Hand-sorted memory chips ensure high performance with generous Overclocking headroom. SPD Speed-2133MHz, Vengeance LPX is optimized for wide compatibility with the latest Intel and AMD DDR4 motherboards. A low-profile height of just 34mm ensures that vengeance LPX even fits in most small-form-factor builds. A high-performance PCB guarantees strong signal quality and stability for superior Overclocking ability. A solid aluminum heatspreader efficiently dissipates heat from each module so that they consistently run at high clock speeds. Supports Intel XMP 2.0 for simple one-setting installation and setup. Available in multiple colors to match the style of your system. Package Memory Pin: 288",
    },
    {
        id: 6,
        name: "Crucial Pro RAM 32GB Kit (2x16GB) DDR5 5600MT/s (or 5200MT/s or 4800MT/s) Desktop Memory CP2K16G56C46U5",
        category: "RAM",
        price: 85,
        image: "/images/products/ramddr5.jpg",
        isCart: false,
        description: "Plug-and-play extreme performance. Downclock capable for systems that only support 5200MT/s or 4800MT/s, Universal compatibility. Compatible with 12th–13th Gen Intel Core or AMD Ryzen 7000 Series desktop CPUs, Supports both Intel XMP 3.0 and AMD EXPO on the same module to recover memory speed if the CPU suppresses it in 4 DIMM configurations, Game at higher frame rates, multitask better, enhance productivity, save time and money, ECC type = non-ECC, form factor = UDIMM, pin count = 288-pin, PC speed = PC5-44800, voltage = 1.1V, rank and configuration = 1Rx8",
    },
    {
        id: 7,
        name: "MSI B550-A PRO ProSeries Motherboard (AMD AM4, DDR4, PCIe 4.0, SATA 6Gb/s, M.2, USB 3.2 Gen 2, HDMI/DP, ATX",
        category: "Motherboard",
        price: 130,
        image: "/images/products/amdmobo.jpg",
        isCart: false,
        description: "Support for 3rd Gen AMD Ryzen processors and future AMD Ryzen processors with BIOS update.Audio ports (Rear) : Realtek ALC892/ALC897 Codec, Supports dual channel DDR4 memory up to 128 GB (4400 MHz). Lightning Fast Game experience: PCIe 4.0, Lightning Gen 4 M.2 with M.2 Shield Frozr, AMD Turbo USB 3.2 GEN 2",
    },
    {
        id: 8,
        name: "ASUS TUF Gaming B760-PLUS WiFi D4 Intel(13th and 12th Gen) LGA 1700 ATX Motherboard,PCIe 5.0,3xPCIe 4.0 M.2 Slots,DDR4,2.5Gb LAN,USB 3.2 Gen 2x2 Type-C,Front USB 3.2 Gen 2 Type-C®, Thunderbolt(USB4®)",
        category: "Motherboard",
        price: 135,
        image: "/images/products/intelmobo.jpg",
        isCart: false,
        description: "Intel LGA 1700 socket: Ready for 13th Gen Intel Core processors & 12th Gen Intel Core, Pentium Gold and Celeron Processors, Enhanced power solution: 12+1 DrMOS power stages, six-layer PCB, 8+4 ProCool sockets, military-grade TUF components and Digi+ VRM for maximum durability. Comprehensive cooling: Enlarged VRM heatsinks, M.2 heatsinks, PCH heatsink, hybrid fan headers and Fan Xpert 4 Latest connectivity: PCIe 5.0 slot, PCIe 4.0 M.2 slots, rear USB 3.2 Gen 2x2 Type-C, front panel header for USB 3.2 Gen 2 Type-C and Thunderbolt (USB4) header support",
    },
];